# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: cockroachdb
  url: <%= ENV.fetch("AUTH_DATABASE_URL") %>
development:
  <<: *default

production:
  adapter: cockroachdb
  url: "cockroachdb://rishi:mq4KLLPUR6P5fl-P5KKucw@absurd-werebat-13764.8nj.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
