runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  RAILS_ENV: 'production'
  AUTH_DATABASE_URL: $AUTH_DATABASE_URL
  DEVISE_JWT_SECRET_KEY: $DEVISE_JWT_SECRET_KEY
  SECRET_KEY_BASE: $SECRET_KEY_BASE_AUTH
  