name: Deploy to Google Cloud From GHCR

on:
  workflow_run:
    workflows: ["Docker Image for Auth Service CI"]  # The name of your CI workflow
    types:
      - completed  # Triggers when the CI workflow has completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_DEPLOY }}
          project_id: meta-geography-243114

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Pull image from GHCR
        run: docker pull ghcr.io/rishirajkumar97/auth-service:latest

      - name: Tag image for Google Artifact Registry
        run: docker tag ghcr.io/rishirajkumar97/auth-service:latest gcr.io/meta-geography-243114/awt_cw/auth-service:latest

      - name: Push image to Google Artifact Registry
        run: docker push gcr.io/meta-geography-243114/awt_cw/auth-service:latest
  deploy_to_app_engine:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    needs: push_to_gcr  # This job runs only after the push_to_gcr job completes
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_DEPLOY }}
          project_id: meta-geography-243114

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --image-url=gcr.io/meta-geography-243114/awt_cw/auth-service:latest --quiet
