name: Docker Image For New Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/fin_webapp/**' # Trigger only if changes occur under src/authenticate-service
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/fin_webapp/**' # Trigger only if changes occur under src/authenticate-service

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        cd src/fin_webapp # Adjust this path to your Rails application directory
        docker build . --file Dockerfile --tag  ghcr.io/rishirajkumar97/news-service:latest
        docker push ghcr.io/rishirajkumar97/news-service:latest
