name: Spin up Instances in GCloud

on:
  workflow_dispatch:
  

jobs:
  spin_up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_DEPLOY }}
          project_id: meta-geography-243114

      - name: Configure Docker
        run: gcloud auth configure-docker
            services=$(gcloud app services list --format="value(id)")
            for service in $services; do
                echo "Starting all stopped versions in service $service"
                versions=$(gcloud app versions list --service="$service" --filter="SERVING_STATUS!=SERVING" --format="value(version.id)")
                for version in $versions; do
                    echo "Starting version $version of service $service"
                    gcloud app versions start $version --quiet
                done
            done